config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  devise_scope :user do
    get 'user/:id', to: 'users/registrations#show'
    get 'signup', to: 'users/registrations#new'
    get 'login', to: 'users/sessions#new'
    get 'logout', to: 'users/sessions#destroy'
  end

  root 'tasks#index'
  resources :tasks
  resources :labels
  resources :task_labels
end

app/models/label.rb
# frozen_string_literal: true

class Label < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
end

app/controllers/labels_controller.rb
# frozen_string_literal: true

class LabelsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_label, only: %i[show edit update destroy]

  def index
    @labels = Label.all
  end

  def show; end

  def new
    @label = Label.new
  end

  def edit; end

  def create
    @label = Label.new(label_params)

    respond_to do |format|
      if @label.save
        format.html { redirect_to label_url(@label), notice: 'ラベルが正常に作成されました' }
        format.json { render :show, status: :created, location: @label }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @label.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @label.update(label_params)
        format.html { redirect_to label_url(@label), notice: 'ラベルが正常に更新されました' }
        format.json { render :show, status: :ok, location: @label }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @label.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @label.destroy

    respond_to do |format|
      format.html { redirect_to labels_url, notice: 'ラベルが正常に削除されました' }
      format.json { head :no_content }
    end
  end

  private

  def set_label
    @label = Label.find(params[:id])
  end

  def label_params
    params.require(:label).permit(:name)
  end
end

app/helpers/labels_helper.rb
# frozen_string_literal: true

module LabelsHelper
end

app/views/labels/_form.html.erb
<%= form_with(model: label) do |form| %>
  <% if label.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(label.errors.count, "error") %> ラベルの保存が出来ませんでした</h2>

      <ul>
        <% label.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label 'ラベル名', style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit '送信' %>
  </div>
<% end %>

app/views/labels/_label.html.erb
<div id="<%= dom_id label %>">
  <p>
    <strong>ラベル名</strong>
    <%= label.name %>
  </p>

</div>

app/views/labels/edit.html.erb
<h1>ラベルを編集する</h1>

<%= render "form", label: @label %>

<br>

<div>
  <%= link_to "ラベルの詳細", @label %> |
  <%= link_to "ラベル一覧に戻る", labels_path %>
</div>

app/views/labels/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>ラベル一覧</h1>

<div id="labels">
  <% @labels.each do |label| %>
    <%= render label %>
    <p>
      <%= link_to "ラベル詳細", label %>
    </p>
  <% end %>
</div>

<%= link_to "ラベルの新規作成", new_label_path %>

app/views/labels/new.html.erb
<h1>ラベルの新規作成</h1>

<%= render "form", label: @label %>

<br>

<div>
  <%= link_to "ラベル一覧に戻る", labels_path %>
</div>

app/views/labels/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @label %>

<div>
  <%= link_to "ラベルを編集する", edit_label_path(@label) %> |
  <%= link_to "ラベル一覧に戻る", labels_path %>

  <%= button_to "ラベルを削除する", @label, method: :delete %>
</div>