config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  devise_scope :user do
    get 'user/:id', to: 'users/registrations#show'
    get 'signup', to: 'users/registrations#new'
    get 'login', to: 'users/sessions#new'
    get 'logout', to: 'users/sessions#destroy'
  end

  root 'tasks#index'
  resources :tasks
  resources :labels
  resources :task_labels
end

app/models/task_label.rb
# frozen_string_literal: true

class TaskLabel < ApplicationRecord
  belongs_to :task
  belongs_to :label
end

app/controllers/task_labels_controller.rb
# frozen_string_literal: true

class TaskLabelsController < ApplicationController
  before_action :set_task_label, only: %i[show edit update destroy]

  def index
    @task_labels = TaskLabel.all
  end

  def show; end

  def new
    @task_label = TaskLabel.new
  end

  def edit; end

  def create
    @task_label = TaskLabel.new(task_label_params)

    respond_to do |format|
      if @task_label.save
        format.html { redirect_to task_label_url(@task_label), notice: 'Task label was successfully created.' }
        format.json { render :show, status: :created, location: @task_label }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task_label.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @task_label.update(task_label_params)
        format.html { redirect_to task_label_url(@task_label), notice: 'Task label was successfully updated.' }
        format.json { render :show, status: :ok, location: @task_label }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task_label.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @task_label.destroy

    respond_to do |format|
      format.html { redirect_to task_labels_url, notice: 'Task label was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_task_label
    @task_label = TaskLabel.find(params[:id])
  end

  def task_label_params
    params.permit(:task_id, :label_id)
  end
end

app/helpers/task_labels_helper.rb
# frozen_string_literal: true

module TaskLabelsHelper
end

app/views/task_labels/_form.html.erb
<%= form_with(model: task_label) do |form| %>
  <% if task_label.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(task_label.errors.count, "error") %> prohibited this task_label from being saved:</h2>

      <ul>
        <% task_label.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/task_labels/_task_label.html.erb
<div id="<%= dom_id task_label %>">
</div>

app/views/task_labels/edit.html.erb
<h1>Editing task label</h1>

<%= render "form", task_label: @task_label %>

<br>

<div>
  <%= link_to "Show this task label", @task_label %> |
  <%= link_to "Back to task labels", task_labels_path %>
</div>

app/views/task_labels/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Task labels</h1>

<div id="task_labels">
  <% @task_labels.each do |task_label| %>
    <%= render task_label %>
    <p>
      <%= link_to "Show this task label", task_label %>
    </p>
  <% end %>
</div>

<%= link_to "New task label", new_task_label_path %>

app/views/task_labels/new.html.erb
<h1>New task label</h1>

<%= render "form", task_label: @task_label %>

<br>

<div>
  <%= link_to "Back to task labels", task_labels_path %>
</div>

app/views/task_labels/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @task_label %>

<div>
  <%= link_to "Edit this task label", edit_task_label_path(@task_label) %> |
  <%= link_to "Back to task labels", task_labels_path %>

  <%= button_to "Destroy this task label", @task_label, method: :delete %>
</div>